/**
 * Attribution line for the export formats that carry comments. It is a comment
 * in every one of them, so it is invisible wherever the file is rendered and
 * present wherever the file is read. CSV and JSON have no comment syntax that
 * every parser tolerates, so they carry no note.
 */
export const GENERATOR_NOTE = "Generated by CRediT Matrix · https://credit.duinlab.nl";
